SmartIP + refactor
InvArch/InvArch-Pallet-Library pull request #95
Opened 2021-12-12 21:02 UTC by arrudagates

This PR will add the custom multisig pallet and the SmartIP pallet, will also refactor the codebase to remove unnecessary crates and change IPT to IPF

2021-12-12 21:14 UTC, arrudagates commented
TODO:

- [ ] Refactor multisig pallet to remove anything unnecessary for InvArch and rewrite what's necessary
- [ ] Properly set weights for everything on pallet_multisig, pallet_smartip and pallet_ips
- [ ] Remove buy, sell, list functions from pallet_ips
- [ ] Write mocks + tests for pallet_multisig and pallet_smartip, rewrite tests on pallet_ips
- [ ] Implement the WASM to WAT + mint IPF of WAT in the pallet_smartip create function ([Reference](https://github.com/InvArch/InvArch-Pallet-Library/blob/gabriel-smartip%2Brefactor/smartip/src/lib.rs#L117-L118))
- [ ] Implement complementary functions on pallet_smartip (delete, amend, etc)
- [ ] On pallet_ips create function, create asset using the IPS account instead of the call author
- [ ] Implement ownership list in the SmartIP create and IPS create functions, defaulting to caller having 100% ownership if not supplied (necessary for the checkbox above)
- [ ] Add a boolean to the IPS structure to identify if it's a SmartIP or a normal IPS

2022-01-18 01:48 UTC, SHA888 requested changes
I guess it just needs a small tweak before the SmartIP is ready to merge, right?

2022-01-18 01:48 UTC, SHA888 commented on ipf/README.md
> +# IPF Pallet: IP Tokens for Substrate
Need to change IP Tokens to IP Files

2022-01-18 01:48 UTC, SHA888 commented on ipf/README.md
> +# IPFokens : Non-fungible components that define an idea.
Same as above (IPFokens to IPFiles)

2022-01-18 01:48 UTC, SHA888 commented on ipf/README.md
> +* `IPFoken` + Metadata
IPFiles

2022-01-18 01:48 UTC, SHA888 commented on ipf/README.md
> +An IP Token (IPF) is a part of a set, and can be thought of as a component of an idea. Either by itself or in combination with other IP Tokens, it serves to strengethen the foundation for an innovati
Same as above

2022-02-05 18:06 UTC, merged